// GENERATED BY HAND: Provides Hive adapter for Employee model.
import 'package:hive/hive.dart';

import 'employee.dart';

class EmployeeAdapter extends TypeAdapter<Employee> {
  @override
  final int typeId = 1;

  @override
  Employee read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    final employee = Employee(
      id: fields[0] as String,
      name: fields[1] as String,
      dailyWage: fields[2] as double,
      phone: fields[3] as String,
      projectId: fields[4] as String,
    );
    employee.isDeleted = fields[5] as bool? ?? false;
    employee.isArchived = fields[6] as bool? ?? false;
    employee.createdAt = fields[7] as DateTime? ?? DateTime.now();
    employee.updatedAt = fields[8] as DateTime?;
    employee.deletedAt = fields[9] as DateTime?;
    return employee;
  }

  @override
  void write(BinaryWriter writer, Employee obj) {
    writer
      ..writeByte(10)
      ..writeByte(0)
      ..write(obj.id)
      ..writeByte(1)
      ..write(obj.name)
      ..writeByte(2)
      ..write(obj.dailyWage)
      ..writeByte(3)
      ..write(obj.phone)
      ..writeByte(4)
      ..write(obj.projectId)
      ..writeByte(5)
      ..write(obj.isDeleted)
      ..writeByte(6)
      ..write(obj.isArchived)
      ..writeByte(7)
      ..write(obj.createdAt)
      ..writeByte(8)
      ..write(obj.updatedAt)
      ..writeByte(9)
      ..write(obj.deletedAt);
  }
}
