// GENERATED BY HAND: Provides Hive adapter for Expense model.
import 'package:hive/hive.dart';

import 'expense.dart';

class ExpenseAdapter extends TypeAdapter<Expense> {
  @override
  final int typeId = 3;

  @override
  Expense read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    final expense = Expense(
      id: fields[0] as String,
      projectId: fields[1] as String,
      description: fields[2] as String,
      amount: fields[3] as double,
      isPaid: fields[4] as bool,
      category: fields[5] as String,
    );
    expense.isDeleted = fields[6] as bool? ?? false;
    expense.isArchived = fields[7] as bool? ?? false;
    expense.createdAt = fields[8] as DateTime? ?? DateTime.now();
    expense.updatedAt = fields[9] as DateTime?;
    expense.deletedAt = fields[10] as DateTime?;
    return expense;
  }

  @override
  void write(BinaryWriter writer, Expense obj) {
    writer
      ..writeByte(11)
      ..writeByte(0)
      ..write(obj.id)
      ..writeByte(1)
      ..write(obj.projectId)
      ..writeByte(2)
      ..write(obj.description)
      ..writeByte(3)
      ..write(obj.amount)
      ..writeByte(4)
      ..write(obj.isPaid)
      ..writeByte(5)
      ..write(obj.category)
      ..writeByte(6)
      ..write(obj.isDeleted)
      ..writeByte(7)
      ..write(obj.isArchived)
      ..writeByte(8)
      ..write(obj.createdAt)
      ..writeByte(9)
      ..write(obj.updatedAt)
      ..writeByte(10)
      ..write(obj.deletedAt);
  }
}
