// GENERATED BY HAND
import 'package:hive/hive.dart';

import 'patron.dart';

class PatronAdapter extends TypeAdapter<Patron> {
  @override
  final int typeId = 4;

  @override
  Patron read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    final patron = Patron(
      id: fields[0] as String,
      name: fields[1] as String,
      phone: fields[2] as String,
      description: fields[3] as String,
    );
    patron.isDeleted = fields[4] as bool? ?? false;
    patron.isArchived = fields[5] as bool? ?? false;
    patron.createdAt = fields[6] as DateTime? ?? DateTime.now();
    patron.updatedAt = fields[7] as DateTime?;
    patron.deletedAt = fields[8] as DateTime?;
    return patron;
  }

  @override
  void write(BinaryWriter writer, Patron obj) {
    writer
      ..writeByte(9)
      ..writeByte(0)
      ..write(obj.id)
      ..writeByte(1)
      ..write(obj.name)
      ..writeByte(2)
      ..write(obj.phone)
      ..writeByte(3)
      ..write(obj.description)
      ..writeByte(4)
      ..write(obj.isDeleted)
      ..writeByte(5)
      ..write(obj.isArchived)
      ..writeByte(6)
      ..write(obj.createdAt)
      ..writeByte(7)
      ..write(obj.updatedAt)
      ..writeByte(8)
      ..write(obj.deletedAt);
  }
}
