// GENERATED BY HAND: Provides Hive adapter for Project model.
import 'package:hive/hive.dart';

import 'project.dart';

class ProjectAdapter extends TypeAdapter<Project> {
  @override
  final int typeId = 0;

  @override
  Project read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    final project = Project(
      id: fields[0] as String,
      name: fields[1] as String,
      patronId: fields[2] as String,
      totalBudget: fields[3] as double,
      defaultDailyWage: fields[4] as double,
      startDate: fields[5] as DateTime,
      endDate: fields[6] as DateTime?,
    );
    project.isDeleted = fields[7] as bool? ?? false;
    project.isArchived = fields[8] as bool? ?? false;
    project.createdAt = fields[9] as DateTime? ?? DateTime.now();
    project.updatedAt = fields[10] as DateTime?;
    project.deletedAt = fields[11] as DateTime?;
    return project;
  }

  @override
  void write(BinaryWriter writer, Project obj) {
    writer
      ..writeByte(12)
      ..writeByte(0)
      ..write(obj.id)
      ..writeByte(1)
      ..write(obj.name)
      ..writeByte(2)
      ..write(obj.patronId)
      ..writeByte(3)
      ..write(obj.totalBudget)
      ..writeByte(4)
      ..write(obj.defaultDailyWage)
      ..writeByte(5)
      ..write(obj.startDate)
      ..writeByte(6)
      ..write(obj.endDate)
      ..writeByte(7)
      ..write(obj.isDeleted)
      ..writeByte(8)
      ..write(obj.isArchived)
      ..writeByte(9)
      ..write(obj.createdAt)
      ..writeByte(10)
      ..write(obj.updatedAt)
      ..writeByte(11)
      ..write(obj.deletedAt);
  }
}
