// GENERATED BY HAND: Provides Hive adapter for WageEntry model.
import 'package:hive/hive.dart';

import 'wage_entry.dart';

class WageEntryAdapter extends TypeAdapter<WageEntry> {
  @override
  final int typeId = 2;

  @override
  WageEntry read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    final entry = WageEntry(
      id: fields[0] as String,
      employeeId: fields[1] as String,
      projectId: fields[2] as String,
      date: fields[3] as DateTime,
      amount: fields[4] as double,
      status: fields[5] as String,
    );
    entry.isDeleted = fields[6] as bool? ?? false;
    entry.isArchived = fields[7] as bool? ?? false;
    entry.createdAt = fields[8] as DateTime? ?? DateTime.now();
    entry.updatedAt = fields[9] as DateTime?;
    entry.deletedAt = fields[10] as DateTime?;
    return entry;
  }

  @override
  void write(BinaryWriter writer, WageEntry obj) {
    writer
      ..writeByte(11)
      ..writeByte(0)
      ..write(obj.id)
      ..writeByte(1)
      ..write(obj.employeeId)
      ..writeByte(2)
      ..write(obj.projectId)
      ..writeByte(3)
      ..write(obj.date)
      ..writeByte(4)
      ..write(obj.amount)
      ..writeByte(5)
      ..write(obj.status)
      ..writeByte(6)
      ..write(obj.isDeleted)
      ..writeByte(7)
      ..write(obj.isArchived)
      ..writeByte(8)
      ..write(obj.createdAt)
      ..writeByte(9)
      ..write(obj.updatedAt)
      ..writeByte(10)
      ..write(obj.deletedAt);
  }
}
